### ISSUE TITLE
Improve built-in /metrics endpoints to use both counter and gauge

### ISSUE THREAD

**Issue by nikitabugrovsky** [pgexporter/pgexporter#32] opened 2022-05-08 15:07 UTC
**Describe the bug**

At the moment `gauge` metric primitive is being hard coded for all exposed metrics:  https://github.com/pgexporter/pgexporter/blob/main/src/libpgexporter/prometheus.c#L1450
we need to be able to to differentiate between different metrics primitives  (counters vs gauges) and report metric type correctly.

**To Reproduce**

1. bin/pgexporter -c /etc/pgexporter/pgexporter.conf -u /etc/pgexporter/pgexporter_users.conf
2. make sure /metrics endpoint is up & running
3. See the following line being reported by pgexporter ` #TYPE <some_metric_name> gauge`

**Version**
pgexporter 0.2.2

**Comment by jesperpedersen** [comment] 2022-05-09 11:09
You will need to go through all the queries and figure out which should be `gauge` and which ones should be `counter`.

I would add this information to https://github.com/pgexporter/pgexporter/blob/main/src/include/queries.h#L51

**Comment by jesperpedersen** [comment] 2022-09-20 10:59
Custom queries have been merged, so they can be used in-place of the built-in ones

**Comment by Aditya0049** [comment] 2023-03-19 16:54
To fix this bug, you need to modify the code of the pgexporter to correctly report the metric types of each metric. Here is a possible approach for doing this:

1. Modify the prometheus.c file to define a new MetricType enum that represents the different types of Prometheus metrics. For example:
**c**
```
typedef enum {
  METRIC_TYPE_COUNTER,
  METRIC_TYPE_GAUGE,
  METRIC_TYPE_HISTOGRAM,
  METRIC_TYPE_SUMMARY,
} MetricType;
```

2. Modify the prometheus.c file to define a new metric_t struct that includes the metric name, value, and type. For example:

```
typedef struct metric_s {
  char *name;
  double value;
  MetricType type;
  struct metric_s *next;
} metric_t;
```

3. Modify the prometheus.c file to add a new **type** parameter to the prom_add_metric() function that specifies the type of the metric being added. For example:

void prom_add_metric(char *name, double value, MetricType type) {
  metric_t *m = prom_find_metric(name);

```
  if (m == NULL) {
    m = malloc(sizeof(metric_t));
    m->name = strdup(name);
    m->value = value;
    m->type = type;
    m->next = metrics;
    metrics = m;
  } else {
    m->value = value;
  }
}
```

4. Modify the prometheus.c file to modify the prom_dump_metrics() function to output the correct type for each metric. For example:

```
void prom_dump_metrics(int fd) {
  metric_t *m;

  for (m = metrics; m != NULL; m = m->next) {
    switch (m->type) {
      case METRIC_TYPE_COUNTER:
        dprintf(fd, "# TYPE %s counter\n", m->name);
        break;
      case METRIC_TYPE_GAUGE:
        dprintf(fd, "# TYPE %s gauge\n", m->name);
        break;
      case METRIC_TYPE_HISTOGRAM:
        dprintf(fd, "# TYPE %s histogram\n", m->name);
        break;
      case METRIC_TYPE_SUMMARY:
        dprintf(fd, "# TYPE %s summary\n", m->name);
        break;
    }
    dprintf(fd, "%s %f\n", m->name, m->value);
  }
}
```

5. Modify the code that calls prom_add_metric() to pass the correct type for each metric. For example:

```
prom_add_metric("my_counter", 42, METRIC_TYPE_COUNTER);
prom_add_metric("my_gauge", 3.14, METRIC_TYPE_GAUGE);
```

6. Test the modified pgexporter to ensure that it correctly reports the metric types of each metric in the /metrics endpoint.


With this approach, you will be able to differentiate between different metric primitives and correctly report their metric types in the /metrics endpoint.

**Comment by jesperpedersen** [comment] 2023-03-20 05:47
Yeah, we need something like this

**Comment by resyfer** [comment] 2023-04-23 07:56
@jesperpedersen For this purpose, I feel the following course of action would be most appropriate:

1) Remove all of the collector functions like [`general_information`](https://github.com/pgexporter/pgexporter/blob/main/src/libpgexporter/prometheus.c#L441) (and the ones below it) or [`primary_information`](https://github.com/pgexporter/pgexporter/blob/main/src/libpgexporter/prometheus.c#L452) (and the ones below it).
2) Specify a `collectors.yml` file that is identical to [this YAML file](https://github.com/pgexporter/pgexporter/blob/main/contrib/yaml/postgresql-10.yaml) till [line 242](https://github.com/pgexporter/pgexporter/blob/main/contrib/yaml/postgresql-10.yaml#L242) which will be kept at a special location (probably in path like `~/.config/pgexporter` or `/etc/pgexporter/collectors.yml`).

Benefits of this would be:
- Shorter, easier to maintain code (I can modify #61 to suite this, and this will work well for a potential solution to #31)
- Removing all of the redundant query-specific code that needs to be maintained for various collectors.
- Easier to make modifications like adding features for #31.
- In order to modify #61, as stated above, I would probably need to add collector tags to the YAML structure for each query, which in turn would extend the "turn off" or "turn on" functionality to custom queries as well.

Disadvantages:
- Losing the compile-time optimizations as the config is loaded first at runtime.
- `collectors.yml` file can be missing, or changed. While the changing can be left to user, missing file error would need to be identified.

**Comment by jesperpedersen** [comment] 2023-04-24 11:11
1. Why ?
2. This is a `pgexporter.conf` thing -- `collectors = general, server`
3. Yes - otherwise it will take the identifier as the collector name
4. Lets worry about YAML later

Do an "example" how it would look configuration-wise... like

```
[pgexporter]
collectors = general, myquery
...

postgresql-10.yml
...
   tag: myquery
```

**Comment by jesperpedersen** [comment] 2023-04-24 11:12
And this issue about "gauge vs counter" support...

**Comment by resyfer** [comment] 2023-04-24 12:48
I'll try to put my idea a bit more clearly. The idea behind it can be summarized in this way:

Since users can already provide custom queries, we can shift the internal queries to use that feature as well. The output will not be different, and the code will follow DRY a bit more and it will be easier to add functionality for both users and internal queries at the same time, and add keep it uniform.

---

The benefit of this in regards to the current issue would be:

Since users can specify the type of the prometheus metric in the YAML file itself and it is reflected in the metrics properly, it will resolve the issue of counter vs gauge. It will also prevent having to add the prometheus metric type 

I'll explain the thing about collectors later. I was just trying to think a bit ahead.

---

Can you provide your feedback for this? If you want, I can add a PR for the corresponding changes, and you can take a look at it for reference.

**Comment by jesperpedersen** [comment] 2023-04-24 12:54
1. If we are running a custom YAML then we can assume that the user wants all of those queries. The problem is the internal ones. Maybe the YAML format should be expanded with a "pgexporter native collectors" section...

2. For internal queries we should know what the correct type is.

Yes, type it up, please

**Comment by resyfer** [comment] 2023-04-29 11:27
@jesperpedersen The following [metrics](https://pgexporter.github.io/metrics.html) need to be counters than gauges imo:

- General
  - pgexporter_state
  - pgexporter_version
  - pgexporter_postgresql_uptime
- pg_stat_bgwriter
  - pgexporter_pg_stat_bgwriter_buffers_alloc
  - pgexporter_pg_stat_bgwriter_buffers_backend
  - pgexporter_pg_stat_bgwriter_buffers_backend_fsync
  - pgexporter_pg_stat_bgwriter_buffers_checkpoint
  - pgexporter_pg_stat_bgwriter_buffers_clean
  - pgexporter_pg_stat_bgwriter_checkpoint_sync_time
  - pgexporter_pg_stat_bgwriter_checkpoint_write_time
  - pgexporter_pg_stat_bgwriter_checkpoints_req
  - pgexporter_pg_stat_bgwriter_checkpoints_timed
  - pg_stat_bgwriter_maxwritten_clean
- pg_stat_database
  - pgexporter_pg_stat_database_blk_read_time
  - pgexporter_pg_stat_database_blk_write_time
  - pgexporter_pg_stat_database_blks_hit
  - pgexporter_pg_stat_database_blks_read
  - pgexporter_pg_stat_database_deadlocks
  - pgexporter_pg_stat_database_tup_returned
  - pgexporter_pg_stat_database_tup_fetched
  - pgexporter_pg_stat_database_tup_inserted
  - pgexporter_pg_stat_database_tup_updated
  - pgexporter_pg_stat_database_tup_deleted
  - pgexporter_pg_stat_database_xact_commit
  - pgexporter_pg_stat_database_xact_rollback
  - pgexporter_pg_stat_database_conflicts
- pg_stat_database_conflicts
  - pgexporter_pg_stat_database_conflicts_confl_tablespace
  - pgexporter_pg_stat_database_conflicts_confl_lock
  - pgexporter_pg_stat_database_conflicts_confl_snapshot
  - pgexporter_pg_stat_database_conflicts_confl_bufferpin
  - pgexporter_pg_stat_database_conflicts_confl_deadlock

Please provide feedback for it, and if the list requires any additions or if it has incorrect entries due to errors in my understanding.

**Comment by Aditya0049** [comment] 2023-04-29 18:42
Based on the metrics you've listed, it seems that your preference for using counters instead of gauges is primarily because you believe that these metrics should always increase and never decrease. While this may be true for some of the metrics you've listed, it's not true for all of them.

For example, the **pgexporter_postgresql_uptime** metric should be a gauge, as it represents the current uptime of the PostgreSQL instance and can decrease if the instance is restarted. Similarly, metrics such as **pgexporter_pg_stat_bgwriter_buffers_alloc**, **pgexporter_pg_stat_bgwriter_buffers_backend**, and **pgexporter_pg_stat_bgwriter_buffers_clean** may decrease if the buffers are released, so they should also be gauges.

That being said, it's important to note that whether a metric should be a gauge or a counter depends on its definition and how it is used. For example, if a metric represents a cumulative value such as the total number of requests processed or the total amount of data transferred, it should be a counter. On the other hand, if a metric represents a current value such as the current number of active connections or the current CPU usage, it should be a gauge.

Therefore, I would suggest reviewing the definitions and usage of the metrics you've listed and determining whether they should be gauges or counters based on their specific characteristics. Additionally, if there are any metrics that you believe should be added to this list, please provide more information on what they represent and how they should be measured.

**Comment by Aditya0049** [comment] 2023-04-29 18:44
Based on the list you provided, I agree with your suggestion that these metrics should be counters rather than gauges:

pg_stat_bgwriter_buffers_alloc
pg_stat_bgwriter_buffers_backend
pg_stat_bgwriter_buffers_backend_fsync
pg_stat_bgwriter_buffers_checkpoint
pg_stat_bgwriter_buffers_clean
pg_stat_bgwriter_checkpoint_sync_time
pg_stat_bgwriter_checkpoint_write_time
pg_stat_bgwriter_checkpoints_req
pg_stat_bgwriter_checkpoints_timed
pg_stat_bgwriter_maxwritten_clean
pg_stat_database_blk_read_time
pg_stat_database_blk_write_time
pg_stat_database_blks_hit
pg_stat_database_blks_read
pg_stat_database_deadlocks
pg_stat_database_tup_returned
pg_stat_database_tup_fetched
pg_stat_database_tup_inserted
pg_stat_database_tup_updated
pg_stat_database_tup_deleted
pg_stat_database_xact_commit
pg_stat_database_xact_rollback
pg_stat_database_conflicts_confl_tablespace
pg_stat_database_conflicts_confl_lock
pg_stat_database_conflicts_confl_snapshot
pg_stat_database_conflicts_confl_bufferpin
pg_stat_database_conflicts_confl_deadlock
Counters are metrics that represent a cumulative value that only ever increases, such as the number of requests or the total number of bytes transferred. In contrast, gauges are metrics that can increase or decrease over time, such as the current number of active connections.

The metrics in the list you provided are all cumulative in nature, so they should be represented as counters rather than gauges.

Overall, your list seems to be comprehensive and accurate. However, it is possible that there are other metrics that could benefit from being represented as counters rather than gauges depending on the specific use case. It's always a good idea to review metrics regularly and adjust their type if necessary.

**Comment by jesperpedersen** [comment] 2023-05-01 05:45
@resyfer Consider the feedback from @Aditya0049 as well as `SELECT pg_stat_reset()'`

**Comment by resyfer** [comment] 2023-05-02 10:38
@Aditya0049 thanks for the feedback and your list. I feel I had made a mistake in judging `pgexporter_pg_stat_bgwriter_buffers_*` metrics. I was slightly confused with the language of the documentation whether it was "total" or "current". Thank you for pointing them out.

Also about `pgexporter_state` and `pgexporter_version`, I couldn't decide whether to assign them as guages or counters, since they don't exactly represent values that are "counters", but at the same time follow the [specification by Prometheus for counters](https://prometheus.io/docs/tutorials/understanding_metric_types/#counter) and hence I added them in the list, though yes, I agree that `rate()` of Prometheus maybe confused by this. Can you please specify which would you like for these two @jesperpedersen?

However I still believe uptime should be kept as a counter as it will only reset to 0 if restarted, which is how counters should behave.

---------------------

@jesperpedersen TIL about pg_stat_reset().

I looked into it, and it seems to me from the [documentation](https://www.postgresql.org/docs/current/monitoring-stats.html#MONITORING-STATS-FUNCTIONS) that it will reset all of the statistics counters to 0 which, I think, also includes `pg_stat_bgwriter`, `pg_stat_database`, `pg_stat_database_conflicts`.

According to the [Prometheus docs](https://www.postgresql.org/docs/current/monitoring-stats.html#MONITORING-STATS-FUNCTIONS) counters can reset to 0, which `pg_stat_reset()` seems to be doing. So I think counters will suit the metrics of the three databases I mentioned above.

**Comment by jesperpedersen** [comment] 2023-05-02 12:16
counter is an increasing value and gauge can increase and decrease.

pgexporter_state is a gauge and pgexporter_version is a counter.

**Comment by resyfer** [comment] 2023-06-09 10:28
@nikitabugrovsky If you feel this issue is resolved, can you please close this?

**Comment by jesperpedersen** [comment] 2023-06-09 13:17
Lets take it on a case-by-case basis now.

Thanks !

**Closed by jesperpedersen** 2023-06-09 13:17 UTC
Labels: enhancement
